Shader "Unlit Master"
{
    Properties
    {
        [NoScaleOffset] Texture2D_B18E1E4("Mask", 2D) = "white" {}
		[NoScaleOffset] _Noise("Noise", 2D) = "white" {}
		[NoScaleOffset] _MainTex("_MainTex", 2D) = "white" {}
		_Speed("Speed ", Float) = -0.3

		_StencilComp("Stencil Comparison", Float) = 8
        _Stencil("Stencil ID", Float) = 0
        _StencilOp("Stencil Operation", Float) = 0
        _StencilWriteMask("Stencil Write Mask", Float) = 255
        _StencilReadMask("Stencil Read Mask", Float) = 255

    }
    SubShader
    {
        Tags
        {
            "RenderPipeline"="LightweightPipeline"
            "RenderType"="Transparent"
            "Queue"="Transparent+0"
        }

		Stencil
        {
            Ref[_Stencil]
            Comp[_StencilComp]
            Pass[_StencilOp]
            ReadMask[_StencilReadMask]
            WriteMask[_StencilWriteMask]
        }

		Cull Off
        Lighting Off
        ZWrite Off
        ZTest[unity_GUIZTestMode]
        Blend SrcAlpha OneMinusSrcAlpha
        ColorMask[_ColorMask]

        Pass
        {
            // Material options generated by graph

            Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha

            Cull Back

            ZTest LEqual

            ZWrite Off

            HLSLPROGRAM
            // Required to compile gles 2.0 with standard srp library
            #pragma prefer_hlslcc gles
            #pragma exclude_renderers d3d11_9x
            #pragma target 2.0

            // -------------------------------------
            // Lightweight Pipeline keywords
            #pragma shader_feature _SAMPLE_GI

            // -------------------------------------
            // Unity defined keywords
            #pragma multi_compile _ DIRLIGHTMAP_COMBINED
            #pragma multi_compile _ LIGHTMAP_ON
            #pragma multi_compile_fog

            //--------------------------------------
            // GPU Instancing
            #pragma multi_compile_instancing
            
            #pragma vertex vert
            #pragma fragment frag

            // Defines generated by graph

            // Lighting include is needed because of GI
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl"
            #include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/Shaders/UnlitInput.hlsl"

            CBUFFER_START(UnityPerMaterial)
            float _Speed;
            CBUFFER_END

            TEXTURE2D(Texture2D_B18E1E4); SAMPLER(samplerTexture2D_B18E1E4); float4 Texture2D_B18E1E4_TexelSize;
            TEXTURE2D(_Noise); SAMPLER(sampler_Noise); float4 _Noise_TexelSize;
            TEXTURE2D(_MainTex); SAMPLER(sampler_MainTex); float4 _MainTex_TexelSize;
            SAMPLER(_SampleTexture2D_5AF65C8B_Sampler_3_Linear_Repeat);
            SAMPLER(_SampleTexture2D_54F4B90F_Sampler_3_Linear_Repeat);
            struct VertexDescriptionInputs
            {
                float3 ObjectSpacePosition;
            };

            struct SurfaceDescriptionInputs
            {
                half4 uv0;
                float3 TimeParameters;
            };


            void Unity_Multiply_float (float A, float B, out float Out)
            {
                Out = A * B;
            }

            void Unity_TilingAndOffset_float(float2 UV, float2 Tiling, float2 Offset, out float2 Out)
            {
                Out = UV * Tiling + Offset;
            }

            void Unity_PolarCoordinates_float(float2 UV, float2 Center, float RadialScale, float LengthScale, out float2 Out)
            {
                float2 delta = UV - Center;
                float radius = length(delta) * 2 * RadialScale;
                float angle = atan2(delta.x, delta.y) * 1.0/6.28 * LengthScale;
                Out = float2(radius, angle);
            }

            void Unity_Add_float(float A, float B, out float Out)
            {
                Out = A + B;
            }

            void Unity_Multiply_float (float4 A, float4 B, out float4 Out)
            {
                Out = A * B;
            }

            struct VertexDescription
            {
                float3 Position;
            };

            VertexDescription PopulateVertexData(VertexDescriptionInputs IN)
            {
                VertexDescription description = (VertexDescription)0;
                description.Position = IN.ObjectSpacePosition;
                return description;
            }

            struct SurfaceDescription
            {
                float3 Color;
                float Alpha;
                float AlphaClipThreshold;
            };

            SurfaceDescription PopulateSurfaceData(SurfaceDescriptionInputs IN)
            {
                SurfaceDescription surface = (SurfaceDescription)0;
                float4 Color_CC07C49C = IsGammaSpace() ? float4(1.990022, 4.335226, 5.340313, 0) : float4(SRGBToLinear(float3(1.990022, 4.335226, 5.340313)), 0);
                float4 _SampleTexture2D_5AF65C8B_RGBA_0 = SAMPLE_TEXTURE2D(Texture2D_B18E1E4, samplerTexture2D_B18E1E4, IN.uv0.xy);
                float _SampleTexture2D_5AF65C8B_R_4 = _SampleTexture2D_5AF65C8B_RGBA_0.r;
                float _SampleTexture2D_5AF65C8B_G_5 = _SampleTexture2D_5AF65C8B_RGBA_0.g;
                float _SampleTexture2D_5AF65C8B_B_6 = _SampleTexture2D_5AF65C8B_RGBA_0.b;
                float _SampleTexture2D_5AF65C8B_A_7 = _SampleTexture2D_5AF65C8B_RGBA_0.a;
                float _Property_6CB193B6_Out_0 = _Speed;
                float _Multiply_802436FE_Out_2;
                Unity_Multiply_float(_Property_6CB193B6_Out_0, IN.TimeParameters.x, _Multiply_802436FE_Out_2);
                float2 _TilingAndOffset_12575A37_Out_3;
                Unity_TilingAndOffset_float(IN.uv0.xy, float2 (1, 1), float2 (0, 0), _TilingAndOffset_12575A37_Out_3);
                float2 _PolarCoordinates_E54568AE_Out_4;
                Unity_PolarCoordinates_float(_TilingAndOffset_12575A37_Out_3, float2 (0.5, 0.5), 1, 1, _PolarCoordinates_E54568AE_Out_4);
                float _Split_F5DF15DF_R_1 = _PolarCoordinates_E54568AE_Out_4[0];
                float _Split_F5DF15DF_G_2 = _PolarCoordinates_E54568AE_Out_4[1];
                float _Split_F5DF15DF_B_3 = 0;
                float _Split_F5DF15DF_A_4 = 0;
                float _Add_D0333679_Out_2;
                Unity_Add_float(_Multiply_802436FE_Out_2, _Split_F5DF15DF_R_1, _Add_D0333679_Out_2);
                float _Add_5A30BB35_Out_2;
                Unity_Add_float(_Split_F5DF15DF_G_2, 0, _Add_5A30BB35_Out_2);
                float2 _Vector2_244C295_Out_0 = float2(_Add_D0333679_Out_2, _Add_5A30BB35_Out_2);
                float4 _SampleTexture2D_54F4B90F_RGBA_0 = SAMPLE_TEXTURE2D(_Noise, sampler_Noise, _Vector2_244C295_Out_0);
                float _SampleTexture2D_54F4B90F_R_4 = _SampleTexture2D_54F4B90F_RGBA_0.r;
                float _SampleTexture2D_54F4B90F_G_5 = _SampleTexture2D_54F4B90F_RGBA_0.g;
                float _SampleTexture2D_54F4B90F_B_6 = _SampleTexture2D_54F4B90F_RGBA_0.b;
                float _SampleTexture2D_54F4B90F_A_7 = _SampleTexture2D_54F4B90F_RGBA_0.a;
                float4 _Multiply_FB1E4DD8_Out_2;
                Unity_Multiply_float(_SampleTexture2D_5AF65C8B_RGBA_0, _SampleTexture2D_54F4B90F_RGBA_0, _Multiply_FB1E4DD8_Out_2);
                float4 _Multiply_2E88F311_Out_2;
                Unity_Multiply_float(Color_CC07C49C, _Multiply_FB1E4DD8_Out_2, _Multiply_2E88F311_Out_2);
                surface.Color = (_Multiply_2E88F311_Out_2.xyz);
                surface.Alpha = (_Multiply_2E88F311_Out_2).x;
                surface.AlphaClipThreshold = 0.5;
                return surface;
            }

            struct GraphVertexInput
            {
                float4 vertex : POSITION;
                float3 normal : NORMAL;
                float4 tangent : TANGENT;
                float4 texcoord0 : TEXCOORD0;
                float4 texcoord1 : TEXCOORD1;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };


            struct GraphVertexOutput
            {
                float4 position : POSITION;

                // Interpolators defined by graph
                float3 WorldSpacePosition : TEXCOORD3;
                float3 WorldSpaceNormal : TEXCOORD4;
                float3 WorldSpaceTangent : TEXCOORD5;
                float3 WorldSpaceBiTangent : TEXCOORD6;
                float3 WorldSpaceViewDirection : TEXCOORD7;
                half4 uv0 : TEXCOORD8;
                half4 uv1 : TEXCOORD9;

                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
            };

            GraphVertexOutput vert (GraphVertexInput v)
            {
                GraphVertexOutput o = (GraphVertexOutput)0;
                UNITY_SETUP_INSTANCE_ID(v);
                UNITY_TRANSFER_INSTANCE_ID(v, o);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);

                // Vertex transformations performed by graph
                float3 WorldSpacePosition = mul(UNITY_MATRIX_M,v.vertex).xyz;
                float3 WorldSpaceNormal = normalize(mul(v.normal,(float3x3)UNITY_MATRIX_I_M));
                float3 WorldSpaceTangent = normalize(mul((float3x3)UNITY_MATRIX_M,v.tangent.xyz));
                float3 WorldSpaceBiTangent = cross(WorldSpaceNormal, WorldSpaceTangent.xyz) * v.tangent.w;
                float3 WorldSpaceViewDirection = _WorldSpaceCameraPos.xyz - mul(GetObjectToWorldMatrix(), float4(v.vertex.xyz, 1.0)).xyz;
                float4 uv0 = v.texcoord0;
                float4 uv1 = v.texcoord1;
                float3 ObjectSpacePosition = mul(UNITY_MATRIX_I_M,float4(WorldSpacePosition,1.0)).xyz;

                VertexDescriptionInputs vdi = (VertexDescriptionInputs)0;

                // Vertex description inputs defined by graph
                vdi.ObjectSpacePosition = ObjectSpacePosition;

                VertexDescription vd = PopulateVertexData(vdi);
                v.vertex.xyz = vd.Position;

                o.position = TransformObjectToHClip(v.vertex.xyz);
                // Vertex shader outputs defined by graph
                o.WorldSpacePosition = WorldSpacePosition;
                o.WorldSpaceNormal = WorldSpaceNormal;
                o.WorldSpaceTangent = WorldSpaceTangent;
                o.WorldSpaceBiTangent = WorldSpaceBiTangent;
                o.WorldSpaceViewDirection = WorldSpaceViewDirection;
                o.uv0 = uv0;
                o.uv1 = uv1;

                return o;
            }

            half4 frag (GraphVertexOutput IN ) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(IN);
        		UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(IN);

                // Pixel transformations performed by graph
                float3 WorldSpacePosition = IN.WorldSpacePosition;
                float3 WorldSpaceNormal = IN.WorldSpaceNormal;
                float3 WorldSpaceTangent = IN.WorldSpaceTangent;
                float3 WorldSpaceBiTangent = IN.WorldSpaceBiTangent;
                float3 WorldSpaceViewDirection = IN.WorldSpaceViewDirection;
                float4 uv0 = IN.uv0;
                float4 uv1 = IN.uv1;

                
                SurfaceDescriptionInputs surfaceInput = (SurfaceDescriptionInputs)0;
                // Surface description inputs defined by graph
                surfaceInput.uv0 = uv0;
                surfaceInput.TimeParameters = _TimeParameters.xyz;


                SurfaceDescription surf = PopulateSurfaceData(surfaceInput);
                float3 Color = float3(0.5, 0.5, 0.5);
                float Alpha = 1;
                float AlphaClipThreshold = 0;
                // Surface description remap performed by graph
                Color = surf.Color;
                Alpha = surf.Alpha;
                AlphaClipThreshold = surf.AlphaClipThreshold;

                
         #if _AlphaClip
                clip(Alpha - AlphaClipThreshold);
        #endif
                return half4(Color, Alpha);
            }
            ENDHLSL
        }
        Pass
        {
            Name "ShadowCaster"
            Tags{"LightMode" = "ShadowCaster"}

            ZWrite On ZTest LEqual

            // Material options generated by graph
            Cull Back

            HLSLPROGRAM
            // Required to compile gles 2.0 with standard srp library
            #pragma prefer_hlslcc gles
            #pragma exclude_renderers d3d11_9x
            #pragma target 2.0

            //--------------------------------------
            // GPU Instancing
            #pragma multi_compile_instancing

            #pragma vertex ShadowPassVertex
            #pragma fragment ShadowPassFragment

            // Defines generated by graph

            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl"
            #include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"

            CBUFFER_START(UnityPerMaterial)
            float _Speed;
            CBUFFER_END

            TEXTURE2D(Texture2D_B18E1E4); SAMPLER(samplerTexture2D_B18E1E4); float4 Texture2D_B18E1E4_TexelSize;
            TEXTURE2D(_Noise); SAMPLER(sampler_Noise); float4 _Noise_TexelSize;
            TEXTURE2D(_MainTex); SAMPLER(sampler_MainTex); float4 _MainTex_TexelSize;
            SAMPLER(_SampleTexture2D_5AF65C8B_Sampler_3_Linear_Repeat);
            SAMPLER(_SampleTexture2D_54F4B90F_Sampler_3_Linear_Repeat);
            struct VertexDescriptionInputs
            {
                float3 ObjectSpacePosition;
            };

            struct SurfaceDescriptionInputs
            {
                half4 uv0;
                float3 TimeParameters;
            };


            void Unity_Multiply_float (float A, float B, out float Out)
            {
                Out = A * B;
            }

            void Unity_TilingAndOffset_float(float2 UV, float2 Tiling, float2 Offset, out float2 Out)
            {
                Out = UV * Tiling + Offset;
            }

            void Unity_PolarCoordinates_float(float2 UV, float2 Center, float RadialScale, float LengthScale, out float2 Out)
            {
                float2 delta = UV - Center;
                float radius = length(delta) * 2 * RadialScale;
                float angle = atan2(delta.x, delta.y) * 1.0/6.28 * LengthScale;
                Out = float2(radius, angle);
            }

            void Unity_Add_float(float A, float B, out float Out)
            {
                Out = A + B;
            }

            void Unity_Multiply_float (float4 A, float4 B, out float4 Out)
            {
                Out = A * B;
            }

            struct VertexDescription
            {
                float3 Position;
            };

            VertexDescription PopulateVertexData(VertexDescriptionInputs IN)
            {
                VertexDescription description = (VertexDescription)0;
                description.Position = IN.ObjectSpacePosition;
                return description;
            }

            struct SurfaceDescription
            {
                float Alpha;
                float AlphaClipThreshold;
            };

            SurfaceDescription PopulateSurfaceData(SurfaceDescriptionInputs IN)
            {
                SurfaceDescription surface = (SurfaceDescription)0;
                float4 Color_CC07C49C = IsGammaSpace() ? float4(1.990022, 4.335226, 5.340313, 0) : float4(SRGBToLinear(float3(1.990022, 4.335226, 5.340313)), 0);
                float4 _SampleTexture2D_5AF65C8B_RGBA_0 = SAMPLE_TEXTURE2D(Texture2D_B18E1E4, samplerTexture2D_B18E1E4, IN.uv0.xy);
                float _SampleTexture2D_5AF65C8B_R_4 = _SampleTexture2D_5AF65C8B_RGBA_0.r;
                float _SampleTexture2D_5AF65C8B_G_5 = _SampleTexture2D_5AF65C8B_RGBA_0.g;
                float _SampleTexture2D_5AF65C8B_B_6 = _SampleTexture2D_5AF65C8B_RGBA_0.b;
                float _SampleTexture2D_5AF65C8B_A_7 = _SampleTexture2D_5AF65C8B_RGBA_0.a;
                float _Property_6CB193B6_Out_0 = _Speed;
                float _Multiply_802436FE_Out_2;
                Unity_Multiply_float(_Property_6CB193B6_Out_0, IN.TimeParameters.x, _Multiply_802436FE_Out_2);
                float2 _TilingAndOffset_12575A37_Out_3;
                Unity_TilingAndOffset_float(IN.uv0.xy, float2 (1, 1), float2 (0, 0), _TilingAndOffset_12575A37_Out_3);
                float2 _PolarCoordinates_E54568AE_Out_4;
                Unity_PolarCoordinates_float(_TilingAndOffset_12575A37_Out_3, float2 (0.5, 0.5), 1, 1, _PolarCoordinates_E54568AE_Out_4);
                float _Split_F5DF15DF_R_1 = _PolarCoordinates_E54568AE_Out_4[0];
                float _Split_F5DF15DF_G_2 = _PolarCoordinates_E54568AE_Out_4[1];
                float _Split_F5DF15DF_B_3 = 0;
                float _Split_F5DF15DF_A_4 = 0;
                float _Add_D0333679_Out_2;
                Unity_Add_float(_Multiply_802436FE_Out_2, _Split_F5DF15DF_R_1, _Add_D0333679_Out_2);
                float _Add_5A30BB35_Out_2;
                Unity_Add_float(_Split_F5DF15DF_G_2, 0, _Add_5A30BB35_Out_2);
                float2 _Vector2_244C295_Out_0 = float2(_Add_D0333679_Out_2, _Add_5A30BB35_Out_2);
                float4 _SampleTexture2D_54F4B90F_RGBA_0 = SAMPLE_TEXTURE2D(_Noise, sampler_Noise, _Vector2_244C295_Out_0);
                float _SampleTexture2D_54F4B90F_R_4 = _SampleTexture2D_54F4B90F_RGBA_0.r;
                float _SampleTexture2D_54F4B90F_G_5 = _SampleTexture2D_54F4B90F_RGBA_0.g;
                float _SampleTexture2D_54F4B90F_B_6 = _SampleTexture2D_54F4B90F_RGBA_0.b;
                float _SampleTexture2D_54F4B90F_A_7 = _SampleTexture2D_54F4B90F_RGBA_0.a;
                float4 _Multiply_FB1E4DD8_Out_2;
                Unity_Multiply_float(_SampleTexture2D_5AF65C8B_RGBA_0, _SampleTexture2D_54F4B90F_RGBA_0, _Multiply_FB1E4DD8_Out_2);
                float4 _Multiply_2E88F311_Out_2;
                Unity_Multiply_float(Color_CC07C49C, _Multiply_FB1E4DD8_Out_2, _Multiply_2E88F311_Out_2);
                surface.Alpha = (_Multiply_2E88F311_Out_2).x;
                surface.AlphaClipThreshold = 0.5;
                return surface;
            }

            struct GraphVertexInput
            {
                float4 vertex : POSITION;
                float3 normal : NORMAL;
                float4 tangent : TANGENT;
                float4 texcoord0 : TEXCOORD0;
                float4 texcoord1 : TEXCOORD1;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };


            struct VertexOutput
            {
                float2 uv           : TEXCOORD0;
                float4 clipPos      : SV_POSITION;
                // Interpolators defined by graph
                float3 WorldSpacePosition : TEXCOORD3;
                float3 WorldSpaceNormal : TEXCOORD4;
                float3 WorldSpaceTangent : TEXCOORD5;
                float3 WorldSpaceBiTangent : TEXCOORD6;
                float3 WorldSpaceViewDirection : TEXCOORD7;
                half4 uv0 : TEXCOORD8;
                half4 uv1 : TEXCOORD9;

                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
            };

            float3 _LightDirection;

            VertexOutput ShadowPassVertex(GraphVertexInput v)
            {
                VertexOutput o;
                UNITY_SETUP_INSTANCE_ID(v);
                UNITY_TRANSFER_INSTANCE_ID(v, o);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);

                // Vertex transformations performed by graph
                float3 WorldSpacePosition = mul(UNITY_MATRIX_M,v.vertex).xyz;
                float3 WorldSpaceNormal = normalize(mul(v.normal,(float3x3)UNITY_MATRIX_I_M));
                float3 WorldSpaceTangent = normalize(mul((float3x3)UNITY_MATRIX_M,v.tangent.xyz));
                float3 WorldSpaceBiTangent = cross(WorldSpaceNormal, WorldSpaceTangent.xyz) * v.tangent.w;
                float3 WorldSpaceViewDirection = _WorldSpaceCameraPos.xyz - mul(GetObjectToWorldMatrix(), float4(v.vertex.xyz, 1.0)).xyz;
                float4 uv0 = v.texcoord0;
                float4 uv1 = v.texcoord1;
                float3 ObjectSpacePosition = mul(UNITY_MATRIX_I_M,float4(WorldSpacePosition,1.0)).xyz;

                VertexDescriptionInputs vdi = (VertexDescriptionInputs)0;

                // Vertex description inputs defined by graph
                vdi.ObjectSpacePosition = ObjectSpacePosition;

                VertexDescription vd = PopulateVertexData(vdi);
                v.vertex.xyz = vd.Position;

                // Vertex shader outputs defined by graph
                o.WorldSpacePosition = WorldSpacePosition;
                o.WorldSpaceNormal = WorldSpaceNormal;
                o.WorldSpaceTangent = WorldSpaceTangent;
                o.WorldSpaceBiTangent = WorldSpaceBiTangent;
                o.WorldSpaceViewDirection = WorldSpaceViewDirection;
                o.uv0 = uv0;
                o.uv1 = uv1;

                
                float3 positionWS = TransformObjectToWorld(v.vertex.xyz);
                float3 normalWS = TransformObjectToWorldNormal(v.normal);

                float4 clipPos = TransformWorldToHClip(ApplyShadowBias(positionWS, normalWS, _LightDirection));

            #if UNITY_REVERSED_Z
                clipPos.z = min(clipPos.z, clipPos.w * UNITY_NEAR_CLIP_VALUE);
            #else
                clipPos.z = max(clipPos.z, clipPos.w * UNITY_NEAR_CLIP_VALUE);
            #endif
                o.clipPos = clipPos;

                return o;
            }

            half4 ShadowPassFragment(VertexOutput IN ) : SV_TARGET
            {
                UNITY_SETUP_INSTANCE_ID(IN);
        		UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(IN);

                // Pixel transformations performed by graph
                float3 WorldSpacePosition = IN.WorldSpacePosition;
                float3 WorldSpaceNormal = IN.WorldSpaceNormal;
                float3 WorldSpaceTangent = IN.WorldSpaceTangent;
                float3 WorldSpaceBiTangent = IN.WorldSpaceBiTangent;
                float3 WorldSpaceViewDirection = IN.WorldSpaceViewDirection;
                float4 uv0 = IN.uv0;
                float4 uv1 = IN.uv1;

                SurfaceDescriptionInputs surfaceInput = (SurfaceDescriptionInputs)0;

        		// Surface description inputs defined by graph
                surfaceInput.uv0 = uv0;
                surfaceInput.TimeParameters = _TimeParameters.xyz;

                SurfaceDescription surf = PopulateSurfaceData(surfaceInput);

        		float Alpha = 1;
        		float AlphaClipThreshold = 0;

        		// Surface description remap performed by graph
                Alpha = surf.Alpha;
                AlphaClipThreshold = surf.AlphaClipThreshold;

         #if _AlphaClip
        		clip(Alpha - AlphaClipThreshold);
        #endif
                return 0;
            }

            ENDHLSL
        }

        Pass
        {
            Name "DepthOnly"
            Tags{"LightMode" = "DepthOnly"}

            ZWrite On
            ColorMask 0

            // Material options generated by graph
            Cull Back

            HLSLPROGRAM
            // Required to compile gles 2.0 with standard srp library
            #pragma prefer_hlslcc gles
            #pragma exclude_renderers d3d11_9x
            #pragma target 2.0

            //--------------------------------------
            // GPU Instancing
            #pragma multi_compile_instancing

            #pragma vertex vert
            #pragma fragment frag

            // Defines generated by graph

            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Lighting.hlsl"
            #include "Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/ShaderGraphFunctions.hlsl"
            #include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"

            CBUFFER_START(UnityPerMaterial)
            float _Speed;
            CBUFFER_END

            TEXTURE2D(Texture2D_B18E1E4); SAMPLER(samplerTexture2D_B18E1E4); float4 Texture2D_B18E1E4_TexelSize;
            TEXTURE2D(_Noise); SAMPLER(sampler_Noise); float4 _Noise_TexelSize;
            TEXTURE2D(_MainTex); SAMPLER(sampler_MainTex); float4 _MainTex_TexelSize;
            SAMPLER(_SampleTexture2D_5AF65C8B_Sampler_3_Linear_Repeat);
            SAMPLER(_SampleTexture2D_54F4B90F_Sampler_3_Linear_Repeat);
            struct VertexDescriptionInputs
            {
                float3 ObjectSpacePosition;
            };

            struct SurfaceDescriptionInputs
            {
                half4 uv0;
                float3 TimeParameters;
            };


            void Unity_Multiply_float (float A, float B, out float Out)
            {
                Out = A * B;
            }

            void Unity_TilingAndOffset_float(float2 UV, float2 Tiling, float2 Offset, out float2 Out)
            {
                Out = UV * Tiling + Offset;
            }

            void Unity_PolarCoordinates_float(float2 UV, float2 Center, float RadialScale, float LengthScale, out float2 Out)
            {
                float2 delta = UV - Center;
                float radius = length(delta) * 2 * RadialScale;
                float angle = atan2(delta.x, delta.y) * 1.0/6.28 * LengthScale;
                Out = float2(radius, angle);
            }

            void Unity_Add_float(float A, float B, out float Out)
            {
                Out = A + B;
            }

            void Unity_Multiply_float (float4 A, float4 B, out float4 Out)
            {
                Out = A * B;
            }

            struct VertexDescription
            {
                float3 Position;
            };

            VertexDescription PopulateVertexData(VertexDescriptionInputs IN)
            {
                VertexDescription description = (VertexDescription)0;
                description.Position = IN.ObjectSpacePosition;
                return description;
            }

            struct SurfaceDescription
            {
                float Alpha;
                float AlphaClipThreshold;
            };

            SurfaceDescription PopulateSurfaceData(SurfaceDescriptionInputs IN)
            {
                SurfaceDescription surface = (SurfaceDescription)0;
                float4 Color_CC07C49C = IsGammaSpace() ? float4(1.990022, 4.335226, 5.340313, 0) : float4(SRGBToLinear(float3(1.990022, 4.335226, 5.340313)), 0);
                float4 _SampleTexture2D_5AF65C8B_RGBA_0 = SAMPLE_TEXTURE2D(Texture2D_B18E1E4, samplerTexture2D_B18E1E4, IN.uv0.xy);
                float _SampleTexture2D_5AF65C8B_R_4 = _SampleTexture2D_5AF65C8B_RGBA_0.r;
                float _SampleTexture2D_5AF65C8B_G_5 = _SampleTexture2D_5AF65C8B_RGBA_0.g;
                float _SampleTexture2D_5AF65C8B_B_6 = _SampleTexture2D_5AF65C8B_RGBA_0.b;
                float _SampleTexture2D_5AF65C8B_A_7 = _SampleTexture2D_5AF65C8B_RGBA_0.a;
                float _Property_6CB193B6_Out_0 = _Speed;
                float _Multiply_802436FE_Out_2;
                Unity_Multiply_float(_Property_6CB193B6_Out_0, IN.TimeParameters.x, _Multiply_802436FE_Out_2);
                float2 _TilingAndOffset_12575A37_Out_3;
                Unity_TilingAndOffset_float(IN.uv0.xy, float2 (1, 1), float2 (0, 0), _TilingAndOffset_12575A37_Out_3);
                float2 _PolarCoordinates_E54568AE_Out_4;
                Unity_PolarCoordinates_float(_TilingAndOffset_12575A37_Out_3, float2 (0.5, 0.5), 1, 1, _PolarCoordinates_E54568AE_Out_4);
                float _Split_F5DF15DF_R_1 = _PolarCoordinates_E54568AE_Out_4[0];
                float _Split_F5DF15DF_G_2 = _PolarCoordinates_E54568AE_Out_4[1];
                float _Split_F5DF15DF_B_3 = 0;
                float _Split_F5DF15DF_A_4 = 0;
                float _Add_D0333679_Out_2;
                Unity_Add_float(_Multiply_802436FE_Out_2, _Split_F5DF15DF_R_1, _Add_D0333679_Out_2);
                float _Add_5A30BB35_Out_2;
                Unity_Add_float(_Split_F5DF15DF_G_2, 0, _Add_5A30BB35_Out_2);
                float2 _Vector2_244C295_Out_0 = float2(_Add_D0333679_Out_2, _Add_5A30BB35_Out_2);
                float4 _SampleTexture2D_54F4B90F_RGBA_0 = SAMPLE_TEXTURE2D(_Noise, sampler_Noise, _Vector2_244C295_Out_0);
                float _SampleTexture2D_54F4B90F_R_4 = _SampleTexture2D_54F4B90F_RGBA_0.r;
                float _SampleTexture2D_54F4B90F_G_5 = _SampleTexture2D_54F4B90F_RGBA_0.g;
                float _SampleTexture2D_54F4B90F_B_6 = _SampleTexture2D_54F4B90F_RGBA_0.b;
                float _SampleTexture2D_54F4B90F_A_7 = _SampleTexture2D_54F4B90F_RGBA_0.a;
                float4 _Multiply_FB1E4DD8_Out_2;
                Unity_Multiply_float(_SampleTexture2D_5AF65C8B_RGBA_0, _SampleTexture2D_54F4B90F_RGBA_0, _Multiply_FB1E4DD8_Out_2);
                float4 _Multiply_2E88F311_Out_2;
                Unity_Multiply_float(Color_CC07C49C, _Multiply_FB1E4DD8_Out_2, _Multiply_2E88F311_Out_2);
                surface.Alpha = (_Multiply_2E88F311_Out_2).x;
                surface.AlphaClipThreshold = 0.5;
                return surface;
            }

            struct GraphVertexInput
            {
                float4 vertex : POSITION;
                float3 normal : NORMAL;
                float4 tangent : TANGENT;
                float4 texcoord0 : TEXCOORD0;
                float4 texcoord1 : TEXCOORD1;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };


            struct VertexOutput
            {
                float2 uv           : TEXCOORD0;
                float4 clipPos      : SV_POSITION;
                // Interpolators defined by graph
                float3 WorldSpacePosition : TEXCOORD3;
                float3 WorldSpaceNormal : TEXCOORD4;
                float3 WorldSpaceTangent : TEXCOORD5;
                float3 WorldSpaceBiTangent : TEXCOORD6;
                float3 WorldSpaceViewDirection : TEXCOORD7;
                half4 uv0 : TEXCOORD8;
                half4 uv1 : TEXCOORD9;

                UNITY_VERTEX_INPUT_INSTANCE_ID
                UNITY_VERTEX_OUTPUT_STEREO
            };

            VertexOutput vert(GraphVertexInput v)
            {
                VertexOutput o = (VertexOutput)0;
                UNITY_SETUP_INSTANCE_ID(v);
                UNITY_TRANSFER_INSTANCE_ID(v, o);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);

                // Vertex transformations performed by graph
                float3 WorldSpacePosition = mul(UNITY_MATRIX_M,v.vertex).xyz;
                float3 WorldSpaceNormal = normalize(mul(v.normal,(float3x3)UNITY_MATRIX_I_M));
                float3 WorldSpaceTangent = normalize(mul((float3x3)UNITY_MATRIX_M,v.tangent.xyz));
                float3 WorldSpaceBiTangent = cross(WorldSpaceNormal, WorldSpaceTangent.xyz) * v.tangent.w;
                float3 WorldSpaceViewDirection = _WorldSpaceCameraPos.xyz - mul(GetObjectToWorldMatrix(), float4(v.vertex.xyz, 1.0)).xyz;
                float4 uv0 = v.texcoord0;
                float4 uv1 = v.texcoord1;
                float3 ObjectSpacePosition = mul(UNITY_MATRIX_I_M,float4(WorldSpacePosition,1.0)).xyz;

                VertexDescriptionInputs vdi = (VertexDescriptionInputs)0;

                // Vertex description inputs defined by graph
                vdi.ObjectSpacePosition = ObjectSpacePosition;

                VertexDescription vd = PopulateVertexData(vdi);
                v.vertex.xyz = vd.Position;

                // Vertex shader outputs defined by graph
                o.WorldSpacePosition = WorldSpacePosition;
                o.WorldSpaceNormal = WorldSpaceNormal;
                o.WorldSpaceTangent = WorldSpaceTangent;
                o.WorldSpaceBiTangent = WorldSpaceBiTangent;
                o.WorldSpaceViewDirection = WorldSpaceViewDirection;
                o.uv0 = uv0;
                o.uv1 = uv1;

                o.clipPos = TransformObjectToHClip(v.vertex.xyz);
                return o;
            }

            half4 frag(VertexOutput IN ) : SV_TARGET
            {
                UNITY_SETUP_INSTANCE_ID(IN);
        		UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(IN);

                // Pixel transformations performed by graph
                float3 WorldSpacePosition = IN.WorldSpacePosition;
                float3 WorldSpaceNormal = IN.WorldSpaceNormal;
                float3 WorldSpaceTangent = IN.WorldSpaceTangent;
                float3 WorldSpaceBiTangent = IN.WorldSpaceBiTangent;
                float3 WorldSpaceViewDirection = IN.WorldSpaceViewDirection;
                float4 uv0 = IN.uv0;
                float4 uv1 = IN.uv1;

                SurfaceDescriptionInputs surfaceInput = (SurfaceDescriptionInputs)0;

        		// Surface description inputs defined by graph
                surfaceInput.uv0 = uv0;
                surfaceInput.TimeParameters = _TimeParameters.xyz;

                SurfaceDescription surf = PopulateSurfaceData(surfaceInput);

        		float Alpha = 1;
        		float AlphaClipThreshold = 0;

        		// Surface description remap performed by graph
                Alpha = surf.Alpha;
                AlphaClipThreshold = surf.AlphaClipThreshold;

         #if _AlphaClip
        		clip(Alpha - AlphaClipThreshold);
        #endif
                return 0;
            }
            ENDHLSL
        }
    }
    FallBack "Hidden/InternalErrorShader"
}
